---
title: "Conclusion"
editor: visual
---

## Summary

Respiratory syncytial virus has been gaining more and more attention since the hospitalization rate has been increasing dramatically while there is no vaccines available now. A reliable regression model will benefit us to better prepare for it.

Our article has generated a model that has a well fit (multiple R square =0.9606 and RMSE=0.16) through polynomial regression analysis. Also, we compared the model based on the data with one year span with two year span, and found that using one year-to-date data could help to build a better model for predicting RSV hospitalization rates. Further researches might be conducted to find out if modeling according to one year-to-data is always better for the seasonal diseases, like RSV.

Furthermore, 3 month future RSV hospitalization rates were calculated. If there is nothing to be done to stop the spread, the hospitalization rates in the next 3 months could be very high, even to 9.

## Limitation

From the polynomial regression approach, we know that it is very sensitive to the outliers. The current high rates might shift our model and affect the results. Second, polynomial may provide good fits within the range of data, but they will frequently deteriorate rapidly outside the range of the data. To gain a better accurate prediction, people need to repeatedly generate new models. Third, In order to model data with a complicated structure, the degree of the model must be high, indicating and the associated number of parameters to be estimated will also be high. This can result in highly unstable models. Other approaches might be applied combined with polynomial regression to attain a more stable model.

From the aspect of the data collection, it only includes 58 counties in 12 states from 2018 to now, it might not give us the whole picture of how respiratory syncytial virus evolved and spread in USA. More data is needed to provide a better prediction.
